### ISSUE TITLE
Flask API implementation (storyteller, wisdomify)

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [wisdomify/wisdomify#104]
## TL;DR
기존에 작성되어 있던 두 API 스크립트를 wisdomify에 integrate 시키자!

## WHY?
스크립트의 플로우가 수정되면서 기존의 스크립트가 수정되어야했다.
storyteller가 wisdomify에 통합되면서 storyteller API 스크립트도 재 작성해야한다.

## WHAT?
`storytellerAPI`,`wisdomifyAPI` 그리고 `main_deploy.py` 구현 

## TODOs
- [x] `storytellerAPI` 구현
- [x] `wisdomifyAPI` 구현
- [x] `main_deploy.py` 구현, 수정
- [x] 배포를 위한 `Dockerfile` 작성

**Comment by ArtemisDicoTiar** [comment]
기존의 각 API 객체를 Flask 객체를 상속받게 하자

**Comment by ArtemisDicoTiar** [comment]
```python
from wisdomify.connectors import connect_to_es
from wisdomify.flows import SearchFlow
```
이 두개만 import하면 바로 아래 에러가 발생한다.
₩₩₩
OSError: [Errno 24] Too many open files
₩₩₩

**Comment by ArtemisDicoTiar** [comment]
`Elasticsearch`만 따로 로드하게 하니 에러 발생하지 않는다
그렇다면 일단 connectors에서는 다른 함수로 인해 발생하는 문제같다.
역시나 `wandb`를 임포트하니 바로 소켓 관련해서 동일한 문제가 발생한다.

**Comment by ArtemisDicoTiar** [comment]
`flows`에서도 wandb 임포트가 있어서 에러가 발생한다.
`storyteller` 검색에 필요한 `flows`객체들만 가져와서 실행하니 문제 없다.
이러면 wandb로 모델 실행은 거의 불가능하다.
우회방법이 필요하다

**Comment by ArtemisDicoTiar** [comment]
@eubinecto 님 위에 코멘트에 작성했듯, wandb만 import하게 되면 소켓 에러 발생시키면서 플라스크가 고장납니다.
좋은 해결방법이 있을까요?

**Comment by eubinecto** [comment]
> @eubinecto 님 위에 코멘트에 작성했듯, wandb만 import하게 되면 소켓 에러 발생시키면서 플라스크가 고장납니다.
> 좋은 해결방법이 있을까요?

플라스크를 사용하는 것이 불가능하다면...wandb는 wandb만의 방법을 따라야할 것 같기도 해요. 
-  https://docs.wandb.ai/guides/self-hosted
여기한번 글 읽어볼래요? 아니면 wandb + deploy로 검색을 좀 해봐야할 것 같아요

**Comment by ArtemisDicoTiar** [comment]
@eubinecto 이거 해결책이 wandb사용안하고 wisdomifier 객체 만들면 성공이거든요?
모델 바이너리랑 토크나이저 설정 같은건 지금 보니깐 wandb에서 링크로 직접 다운로드 가능하니깐 그걸로 하면 되는 데
지금 flow가 안 익숙해서 어떤 흐름으로 동작되는 지 모르겠어요
wandb 사용 안하고 wisdomifier 만드는 코드 써주실수 있나요 (dir설정하는 거 같은건 빈칸으로 두셔도 됩니다 제가 채울게요)

**Comment by ArtemisDicoTiar** [comment]
@eubinecto 위에 에러 신경 안쓰셔도 됩니다 오늘 회의에서 있었던것도 무시해주세요
플라스크 디버깅 켜놓고 돌리고 있었는데 디버깅 끄니깐 원하는 대로 돌아갑니다

**Comment by ArtemisDicoTiar** [comment]
이전에 있던 문제는 추측컨데
wandb socket + debugging socket (flask에서 만든 디버깅) + flask socket (서비스 소켓)
요렇게 구성하다 충돌한거 같다
완디비를 쓰거든 플라스크 디버깅은 반드시 False로

**Comment by ArtemisDicoTiar** [comment]
## Deploy 완료

https://feature-104-wisdomify-eubinecto.endpoint.ainize.ai/

## Specification
### /wisdomify
- param: 없음
- body:
  - sent: "검색할 문장"
  - 
### /storytell
- param: 없음
- body:
  - wisdom: "검색할 속담"

**Comment by ArtemisDicoTiar** [comment]
PR에서 나온 요청사항 반영후 재 배포 완료
