### ISSUE TITLE
[API]: Definition endpoint

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [wisdomify/wisdomify#111]
## TL;DR
정의 가져오는 엔드포인트가 필요하다
스크립트중에 정의만 가져오는 게 있을 텐데 그걸 바탕으로 구축해보자.

**Comment by eubinecto** [comment]
`WisdomsFlow`를 사용하면 됩니다! 그런데 이것도 미리 로드를 해놓아야 할거에요.
