### ISSUE TITLE
`FC` 와 `Linear` 의 차이?

### ISSUE THREAD

**Issue by eubinecto** [wisdomify/wisdomify#124]
## Why?

그냥 궁금하다. 미리 flatten을 하고 행렬 곱을 하는거랑,  flatten을 하지 않는 것이랑 무슨차이가 있을까?

예를 들면 이렇게 FC를 사용해서 풀링하는 것:
https://github.com/wisdomify/wisdomify/blob/aafd439b8028510b870882357e35670d848c21af/explore/explore_fc_vs_linear.py#L12-L16

반면 linear layer를 사용해서도 같은 풀링을 하는 것도 가능함:
https://github.com/wisdomify/wisdomify/blob/aafd439b8028510b870882357e35670d848c21af/explore/explore_fc_vs_linear.py#L18-L20

그렇다면... 둘이 뭐가 어떻게 다른걸까?

**Comment by ArtemisDicoTiar** [comment]
## Number of params?

### code
~~~python
import torch

K = 10
H = 20

fc = torch.nn.Sequential(
    torch.nn.Flatten(),
    torch.nn.Linear(in_features=K * H, out_features=H)
)
linear = torch.nn.Linear(in_features=K, out_features=H)

print(f"* fc params:")
for fc_p in fc.parameters():
    print(f"\t\t{fc_p.size()}")

print(f"* linear params:")
for l_p in linear.parameters():
    print(f"\t\t{l_p.size()}")
~~~


### result
~~~bash
* fc params:
		torch.Size([20, 200])
		torch.Size([20])
* linear params:
		torch.Size([20, 10])
		torch.Size([20])
~~~

근데 
~~~python
 linear_layer = torch.nn.Linear(in_features=K, out_features=H) 
 wisdom_embeddings = linear_layer(torch.einsum("wkh->whk", wisdom_embeddings)).squeeze() 
~~~
이걸 수행하면 
(W, K, H) -> (W, H, K) -> (W, H, H) 아닌가?
(linear layer가 3rd dim에 적용된다고 했을때)
(W, K, H) -> (W, H, K) -> (W, H, 1) 을 achieve하고 싶다면 
linear layer가 K → 1 여야할 거 같은데...
