### ISSUE TITLE
wisdom2def 데이터가 가지는 가치, 의미가 무엇인가..?

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [wisdomify/wisdomify#56]
### Training
[~~~~] := [MASK]
* [속담] {정의}
* [갈수록 태산] {어떤일의 형태가 갈수록 점점 더 힘들어짐}

### Infer
* [갈수록 태산]인게 {오늘 직장을 잃었는 데, 집주인이 집세를 올려달라고 해} ~~흑흑 ㅠㅠ~~

트레이닝에서는 정의 ←→ 속담의 관계만 보여준 거 같은데
1. 왜 인퍼에서 용례 → 속담 이게 가능한건지?

2. 정의 데이터의 가지고 있는 의미와 가치가 뭐길래…?

## What?
1. wisdom2def 데이터가 가지는 가치와 의미?
2. 인퍼에서 용래 → 속담이 "정의 ←→속담”만 트레이닝한 모델에서 되는 이유?

**Comment by ArtemisDicoTiar** [comment]
## 용어 정리
* 정의
  * 어떤 대상의 뜻을 밝혀서 풀이하는 설명방법
  * 대상의 의미를 명확히 알 수 있도록 함.
* 예시
  * 대상과 연관된 구체적이고 친근한 사례를 제시하여 설명하는 방법
  * 구체적인 사례를 통해 설명 대상에 대한 이해를 더욱 쉽게 할 수 있다.

**Comment by ArtemisDicoTiar** [comment]
## 정의의 가치 >> 용례의 가치다.
~~양치하다 생각났다~~
word =: definition
상호 교환 가능 관계?

왜냐하면 
정의는 word := definition의 관계로 둘을 바꿔도 말이된다. 그 말인 즉슨 정의는 속담의 전부를 설명하는 말이다.
이걸 프로그래밍적으로 정의해보면
~~~python
class word:
    prop1
    prop2
    prop3
    prop4
    prop5
~~~
의 형태를 띄는 word가 있을 때, 
definition은 (prop1 & prop2 & prop3 & prop4 & prop5)의 의미를 갖는 문장인 것이다.

반면에 용례의 경우, Duck typing과 같은 형태를 보인다.
이것 역시 프로그래밍적으로 적어보면
~~~python
class example1:
    prop1’
    prop2’
    prop4'
~~~
의 형태를 띈다.

이 말인즉, 용례는 word (:= definition)이 가지고 있는 모든 prop을 가지고 있지 않을 수 있다.
그렇기 때문에 용례가 덜 자세해질 수록 (prop 개수가 줄어들수록) 우리가 생각하는 word와 어울리지 않아 보이는 것이다. (거리가 멀어진다. 수학적 벡터값으로 표현된다면.)

예를 들면
* word: 교통수단
* def: 사람이 이동하거나 짐을 옮기는 데 쓰는 수단.
* 좋은 eg: 낙타는 사막에서 짐을 싣고 나르는 모습을 자주 보인다.
  * 좋은 예시인 이유: 정의에서 말한 prop인 “짐”, “나르는(~=옮기는)”을 포함하고 있다.
* 안 좋은 eg: 자전거를 타고 있는 올림픽 선수 (이 선수가 출근을 하기 위해 길에서 타고 있는 사진의 주석으로 해당 문장이 달렸다고 하자.)
  * 안 좋은 예시인 이유:
    * 해당 문장의 prop중 “사람”, “타고있는 (이동)”이라는 의미를 포함하고 있으나 “올림픽”이라는 단어와 “자전거”라는 단어의 조합으로 하여금 교통수단보다는 올림픽 경기라는 의미에 좀더 가까워 보인다.
    * 즉, 올림픽이라는 단어가 가진 weight이 크게 작용한 케이스.
    * 결국 원래 목표로 한 단어와 거리가 멀어졌다.

이걸 쓰다 보니 word2vec같은 느낌이 든다.
어?
이 논리가 맞을 지 모르겠지만 적어본다.

== TRAIN ==
BERT는 embedding된 토큰을 입력받는다. (Vector)
정의 토큰 중 word (MASK)의 prop에 해당되는 부분들이 있을 것이다.
그 부분을 모델은 학습.
내부 embedding 값을 learning한다고 했으니 이런걸 배우는 게 가능 할지도 모름.

== INFER ==
용례 → 임베딩/토크나이징 → 모델 입력
모델은 용례의 벡터를 보고 해당 용례의 prop에 해당되는 부분을 이해/추출
→ 이 prop에 해당되는 벡터에 가까운 토큰들을 마스크에 씌움

**Comment by eubinecto** [comment]
# 일단 현재 계획
1. 용례만  데이터로 사용한 모델
2. 용례와 정의를 데이터로 사용한 모델
2. 용례만 데이터로, 하지만 정의는 레이블로 사용한 모델

이 세 모델을 만들어보고, 비교해보자.

**Comment by eubinecto** [comment]
![image](https://user-images.githubusercontent.com/56193069/134121094-6e00a4af-6c23-45cb-a109-479171925575.jpeg)


- 용례 데이터: MLM으로 의미의 느낌을 학습 
- 정의 데이터: 느낌을 정의로 미세조정
