### ISSUE TITLE
metaflow 적용 & storyteller 병합

### ISSUE THREAD

**Issue by eubinecto** [wisdomify/wisdomify#98]

**Comment by ArtemisDicoTiar** [comment]
@eubinecto 시간이 괜찮다면 금욜 회의때 메타플로우에 대해 간략하게 얘기해줄 수 있나요?

**Comment by eubinecto** [comment]
> @eubinecto 시간이 괜찮다면 금욜 회의때 메타플로우에 대해 간략하게 얘기해줄 수 있나요?

얼마든지요!! 그런데 메타플로우는 쓰려고 했다가.. 괜히 프로젝트가 복잡해져서 그냥 제거했어요

**Comment by eubinecto** [comment]
torch.load와 load_state_dict를 사용하는게 아니라, pytorch lightning에서 지원하는 save_checkpoints로 모델을 저장하는 편이 나을듯. 그렇게 하는 경우, wisdom2subwords, wiskeys 같은 상수 텐서도 하이퍼파라미터로 저장 & 로드할 수 있다!
